coverage:
    status:
        project:
            default: off
            apps:
                flags: apps
            packages:
                flags: packages
                threshold: 60

flags:
    apps:
        paths:
            - apps/api
            - apps/web
    packages:
        paths:
            - packages/error-flow

