language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/web/node_modules

before_install:
  - npm install -g codecov lerna
  - lerna bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: Lint
      script:
            - lerna run lint
            - lerna run typecheck
    - stage: Web
      script:
          - lerna run --scope @bluewind/web build
    - stage: Api
      script:
          - lerna run --scope @bluewind/api build


