language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/frontend/node_modules

before_install:
  - npm install -g codecov lerna
  - lerna bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: Api
      script:
        - npm run build --prefix=apps/api
    - stage: Frontend
      script:
          - npm run build --prefix=apps/frontend
    - stage: Lint
      script:
            - lerna run lint

