language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/web/node_modules
    - packages/error-flow/node_modules
    - packages/error-flow/dist

before_install:
  - npm install -g codecov
  - yarn install
  - yarn bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: "@bluewind/[*]"
      script:
          - yarn lerna run --scope "@bluewind/*" test --stream
          - yarn lerna run --scope "@bluewind/*" build --stream
    - stage: "@bluewind-app/web"
      script:
          - yarn lerna run --scope @bluewind-app/web test
          - yarn lerna run --scope @bluewind-app/web build
          - yarn lerna run --scope @bluewind-app/web es-check
    - stage: "@bluewind-app/api"
      script:
          - yarn lerna run --scope @bluewind-app/api test
          - yarn lerna run --scope @bluewind-app/api build
    - stage: CodeStyle
      script:
          - yarn lint


