language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/web/node_modules
    - packages/*/node_modules
    - packages/*/dist

before_install:
  - npm install -g codecov
  - yarn install
  - yarn bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: "@bluewind/packages"
      script:
          - yarn lerna run --scope @bluewind/error-flow test
          - yarn lerna run --scope @bluewind/error-flow build
    - stage: "@bluewind-app/web"
      script:
          - yarn lerna run --scope @bluewind/web test
          - yarn lerna run --scope @bluewind/web build
          - yarn lerna run --scope @bluewind/web es-check
    - stage: "@bluewind-app/api"
      script:
          - yarn lerna run --scope @bluewind/api test
          - yarn lerna run --scope @bluewind/api build
    - stage: CodeStyle
      script:
          - yarn lint


