language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/web/node_modules

before_install:
  - npm install -g codecov
  - yarn install
  - yarn bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: CodeStyle
      script:
            - yarn lint
            #- yarn typecheck
    - stage: Packages
      script:
          - yarn lerna run --scope @bluewind/web test
          - yarn lerna run --scope @bluewind/error-flow build
    - stage: Web
      script:
          - yarn lerna run --scope @bluewind/web test
          - yarn lerna run --scope @bluewind/web build
          - yarn lerna run --scope @bluewind/web es-check
    - stage: Api
      script:
          - yarn lerna run --scope @bluewind/api test
          - yarn lerna run --scope @bluewind/api build


