language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules
    - apps/api/node_modules
    - apps/web/node_modules
    - packages/error-flow/node_modules
    - packages/error-flow/dist

before_install:
  - npm install -g codecov
  - yarn install
  - yarn bootstrap

jobs:
  allow_failures:
    - stage: Lint
  include:
    - stage: "@bluewind/packages (all)"
      script:
          - yarn lerna run --scope "@bluewind/*" test --stream
          - yarn lerna run --scope "@bluewind/*" build --stream
    - stage: "bluewind-web"
      script:
          - yarn workspace bluewind-web test:coverage
          - cd apps/web && codecov -cF apps-web && cd ../..
          - yarn workspace bluewind-web build
          - yarn workspace bluewind-web es-check
    - stage: "bluewind-api"
      script:
          - yarn workspace bluewind-api test
          - yarn workspace bluewind-api build
    - stage: CodeStyle
      script:
          - yarn lint


