name: All tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Install & bootstrap"
      run: |
        yarn install --frozen-lockfile
        yarn bootstrap
    - name: "Build packages"
      run: |
        yarn build:packages
      env:
        CI: true
    - name: "Tests"
      run: |
        yarn lerna run test:coverage
      env:
        CI: true
    #- name: Send coverage
    #  working-directory: .
    #  run: |
    #      cat .codecov.yml | curl --data-binary @- https://codecov.io/validate
    #      npm install -g codecov
    #      CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} yarn coverage:publish
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: apps,packages
          yml: ./.codecov.yml
          fail_ci_if_error: true
    - name: "Lint & typecheck"
      run: |
        yarn typecheck
        yarn lint
    - name: "Build & es-check"
      run: |
        yarn lerna run --scope bluewind-api build
        yarn lerna run --scope bluewind-web build
        yarn lerna run --scope bluewind-web es-check
      env:
        CI: true
