name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Install & bootstrap"
      run: |
        yarn install
        yarn bootstrap
    - name: "Build packages"
      run: |
        yarn build:packages
      env:
        CI: true
    - name: "Tests"
      run: |
        yarn workspace bluewind-web test:coverage
        yarn workspace @bluewind/error-flow test:coverage
      env:
        CI: true
    - name: Send coverage
      working-directory: .
      run: |
          cat .codecov.yml | curl --data-binary @- https://codecov.io/validate
          npm install -g codecov
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} yarn coverage:publish
    - name: "Lint & typecheck"
      run: |
        yarn typecheck
        yarn lint
    - name: "Build & es-check"
      run: |
        yarn lerna run --scope bluewind-api build
        yarn lerna run --scope bluewind-web build
        yarn lerna run --scope bluewind-web es-check
      env:
        CI: true
